/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/taramana/dual/new/opt/karamel/krml -dast extracted/CBOR_Pulse_Raw_Type.krml
  F* version: <unknown>
  KaRaMeL version: d7a8f9ec
 */

#ifndef CBOR_Pulse_Raw_Type_H
#define CBOR_Pulse_Raw_Type_H

#include "krmllib.h"

typedef struct CBOR_Pulse_Raw_Type_cbor_int_s
{
  uint8_t cbor_int_type;
  CBOR_Spec_Raw_Base_integer_size cbor_int_size;
  uint64_t cbor_int_value;
}
CBOR_Pulse_Raw_Type_cbor_int;

typedef struct CBOR_Pulse_Raw_Type_cbor_raw_s CBOR_Pulse_Raw_Type_cbor_raw;

typedef struct CBOR_Pulse_Raw_Type_cbor_tagged_s
{
  CBOR_Spec_Raw_Base_raw_uint64 cbor_tagged_tag;
  CBOR_Pulse_Raw_Type_cbor_raw *cbor_tagged_ptr;
}
CBOR_Pulse_Raw_Type_cbor_tagged;

typedef struct CBOR_Pulse_Raw_Type_cbor_map_entry_s
{
  CBOR_Pulse_Raw_Type_cbor_raw cbor_map_entry_key;
  CBOR_Pulse_Raw_Type_cbor_raw cbor_map_entry_value;
}
CBOR_Pulse_Raw_Type_cbor_map_entry;

#define CBOR_Pulse_Raw_Type_CBOR_Case_Int 0
#define CBOR_Pulse_Raw_Type_CBOR_Case_Simple 1
#define CBOR_Pulse_Raw_Type_CBOR_Case_String 2
#define CBOR_Pulse_Raw_Type_CBOR_Case_Tagged 3
#define CBOR_Pulse_Raw_Type_CBOR_Case_Array 4
#define CBOR_Pulse_Raw_Type_CBOR_Case_Map 5
#define CBOR_Pulse_Raw_Type_CBOR_Case_Serialized_Tagged 6
#define CBOR_Pulse_Raw_Type_CBOR_Case_Serialized_Array 7
#define CBOR_Pulse_Raw_Type_CBOR_Case_Serialized_Map 8

typedef uint8_t CBOR_Pulse_Raw_Type_cbor_raw_tags;

typedef struct CBOR_Pulse_Raw_Type_cbor_raw_s
{
  CBOR_Pulse_Raw_Type_cbor_raw_tags tag;
  union {
    CBOR_Pulse_Raw_Type_cbor_int case_CBOR_Case_Int;
    uint8_t case_CBOR_Case_Simple;
    CBOR_Pulse_Raw_Type_cbor_string case_CBOR_Case_String;
    CBOR_Pulse_Raw_Type_cbor_tagged case_CBOR_Case_Tagged;
    CBOR_Pulse_Raw_Type_cbor_array case_CBOR_Case_Array;
    CBOR_Pulse_Raw_Type_cbor_map case_CBOR_Case_Map;
    CBOR_Pulse_Raw_Type_cbor_serialized case_CBOR_Case_Serialized_Tagged;
    CBOR_Pulse_Raw_Type_cbor_serialized case_CBOR_Case_Serialized_Array;
    CBOR_Pulse_Raw_Type_cbor_serialized case_CBOR_Case_Serialized_Map;
  }
  ;
}
CBOR_Pulse_Raw_Type_cbor_raw;


#define CBOR_Pulse_Raw_Type_H_DEFINED
#endif /* CBOR_Pulse_Raw_Type_H */
