on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .docker/build/linux/Dockerfile.everest-hub --build-arg CI_THREADS=16
